
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import MenuContextProvider from "@/context/MenuContext";
import LoginPage from "./Login/page";

export const metadata = {
  title: "HUNTERRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body/>
     {/*  <LoginPage>

      </LoginPage>  */}
     <MenuContextProvider>
     
     <MainLayout>
         {children}
       </MainLayout>


     </MenuContextProvider> 
    </html>
    
  );
}
