
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import MenuContextProvider from "@/context/MenuContext";

export const metadata = {
  title: "HUNTERRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      
      <MenuContextProvider>
     
      <MainLayout>
          {children}
        </MainLayout>


      </MenuContextProvider>
        
        
       

      </body>
    </html>
  );
}
